---
repos:
  # - repo: local
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       entry: pylint
  #       language: system
  #       types: [python]
  #       args:
  #         [
  #           "-rn", # Only display messages
  #           "-sn", # Don't display the score
  #         ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: detect-private-key
      - id: sort-simple-yaml
      - id: mixed-line-ending
      - id: double-quote-string-fixer
      - id: pretty-format-json
      - id: debug-statements
      - id: requirements-txt-fixer
        args: [--autofix]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: shellcheck
      - id: script-must-have-extension
      - id: shfmt
      - id: forbid-binary
