name: Docker container

on:
  push:
    paths-ignore:
        - '**/*.md'
        - '**/*.yaml'
        - '.github/**'
        - '.devcontainer/**'
        - '**/*.env'
    # tags:
    #   - 'v*.*.*'
    # branches:
    #   - release/*
  release:
    types: [published]

jobs:

  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        language: [ 'python' ]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          antaresinc/magnet2torrent
        # generate Docker tags based on the following events/attributes
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,event=tag
        #  type=sha
        flavor: |
          latest=auto

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
      uses: anchore/scan-action@ecfd0e98932e57ea8f68f29c4f418fc41a8194db
      with:
        path: "."
        acs-report-enable: true
        fail-build: true
        severity-cutoff: critical
    - name: Upload Anchore Scan Report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
