name: Docker container

on:
  push:
    paths-ignore:
        - '**/*.md'
        - '**/*.yaml'
        - '.github/**'
        - '**/*.env'
    branches:
      - 'main'
      - 'ui**'
      - 'web/ui**'
      - 'feature/**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:

  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        language: [ 'python' ]
    steps:
    - uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          antaresinc/magnet2torrent
        # generate Docker tags based on the following events/attributes
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,event=tag
          type=ref,event=branch
        #  type=sha
        flavor: |
          latest=auto

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
      uses: anchore/scan-action@d39ae4a9588ccc72ce55bb78778bda34f1209f08
      with:
        path: "."
        acs-report-enable: true
        fail-build: true
        severity-cutoff: critical
    - name: Upload Anchore Scan Report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
